services:
  chat_api:
    image: chat_api_image
    container_name: chat_api_container
    build: ./
    env_file:
      - ../../setting.conf
    secrets:
      - apiKey.key
    volumes:
      - ./src/:/chat_api/src/ #TODO remove in production
    # ports:
    #   - 3002:3002 # TODO remove this in production
    networks:
      - Transcendence2.0
    depends_on:
      - chat_db
    restart: unless-stopped
secrets:
  apiKey.key:
    file: api_key/apiKey.key
