services:
  pong-api:
    image: pong-api-img 
    container_name: pong-api
    build:
      context: ..
      dockerfile: pong-api/Dockerfile
    volumes:
      - ./src/:/pong/pong-api/src/
    ports:
      - 3010:3010
    command: ["npm", "--prefix", "/pong/pong-api/", "run", "dev"]
    networks:
      - Transcendence2.0


networks:
  Transcendence2.0: 
    external: true  #REMOVE external network if we use 1 single docker-compose for all services
