services:
  pong-api:
    image: pong-api-img 
    container_name: pong-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/pong/pong-api/src/
    ports:
      - 3010:3010
    command: ["npm", "--prefix", "/pong/pong-api/", "run", "dev"]