services:
  tailwind:
    container_name: tailwind
    image: tailwind-img
    build:
      context: ./
      dockerfile: docker/tailwind/Dockerfile-Tailwind
    volumes:
      - ./volume:/app/volume
    restart: unless-stopped
    networks:
      - general
networks:
  general:
    driver: bridge
