services:
  tailwind:
    container_name: tailwind
    image: tailwind-img
    build:
      context: ./
      dockerfile: docker/tailwind/Dockerfile-Tailwind
    volumes:
      - ./volume:/app/volume
    restart: unless-stopped
  typescript:
    container_name: typescript
    image: typescript-img
    build:
      context: ./
      dockerfile: docker/typescript/Dockerfile-Typescript
    volumes:
      - ./volume:/app/volume
    restart: unless-stopped
