services:
  pong-api:
    image: pong-api-img
    container_name: pong-api
    build:
      context: ./ssg/pong-api
      dockerfile: Dockerfile
    volumes:
      - ./ssg/pong-api/src/:/pong/pong-api/src/
    ports:
      - 3010:3010 #TODO remove it will not be exposed at final version
    environment:
      - NODE_ENV=production
    command: ["npm", "--prefix", "/pong/pong-api/", "run", "pong-api"]
    networks:
      - Transcendence2.0

  ai-bot:
    image: ai-bot
    build:
      context: ./ssg
      dockerfile: ./AI/Dockerfile
    container_name: ai-bot
    environment:
      - NODE_ENV=production
    ports:
      - 6969:6969 #TODO keep now for swagger documentation, remove later
    networks:
      - Transcendence2.0

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/nginx/Dockerfile-Nginx
    container_name: frontend
    # image: nginx:1.26.2
    volumes:
      - ./frontend/volume:/usr/share/nginx/html
      - ./frontend/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:443"
    restart: unless-stopped
    networks:
      - Transcendence2.0

include:
  - ./microservices/auth_api/docker-compose.yml
  - ./frontend/docker-compose.yml
  - ./monitoring/monitoring-docker-compose.yml
  - ./microservices/users/docker-compose.yml
  - ./microservices/pong_db/docker-compose.yml
  - ./microservices/chat_db/docker-compose.yml
  - ./microservices/chat_api/docker-compose.yml
  - ./microservices/tictactoe_db/docker-compose.yml
  - ./microservices/tictactoe_api/docker-compose.yml

networks:
  Transcendence2.0:
