services:
  pong-api:
    image: pong-api-img
    container_name: pong-api
    build:
      context: ./ssg/pong-api
      dockerfile: Dockerfile
    volumes:
      - ./ssg/pong-api/src/:/pong/pong-api/src/
    ports:
      - 3010:3010 #TODO remove it will not be exposed at final version
    command: ["npm", "--prefix", "/pong/pong-api/", "run", "dev"]
    networks:
      - Transcendence2.0
  ai-bot:
    build:
      context: ./ssg
      dockerfile: ./AI/Dockerfile
    container_name: ai-bot
    environment:
      - NODE_ENV=production
    ports:
      - 6969:6969 #TODO keep now for swagger documentation, remove later
    networks:
      - Transcendence2.0

  chat_api:
    image: chat_api_img
    container_name: chat_api_container
    build: ./chat_api
    volumes:
      - ./chat_api/src:/chat_api/src
    ports:
      - "3002:3002" # TODO remove it will not be exposed at final version
    depends_on:
      - chat_db
    networks:
      - Transcendence2.0
    restart: always

  chat_db:
    image: chat_db_image
    container_name: chat_db_container
    build: ./chat_db
    environment:
      - DATABASE_URL=file:/chat_db/DB/chatDB.db
    volumes:
      - ./chat_db/src/:/chat_db/src/ # TODO remove in production
      - ./chat_db/prisma/:/chat_db/prisma/ # TODO remove in production
      # - /home/iguliyev/DBs/chat/:/chat_db/DB/ # TODO edit host path and uncomment this line in production
    ports:
      - 3004:3004 # TODO remove it will not be exposed at final version
    networks:
      - Transcendence2.0
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/nginx/Dockerfile-Nginx
    container_name: frontend
    # image: nginx:1.26.2
    volumes:
      - ./frontend/volume:/usr/share/nginx/html
      - ./frontend/docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      # - ./src/frontend/docker/certificate/localhost.key:/etc/nginx/localhost.key
      # - ./src/frontend/docker/certificate/localhost.crt:/etc/nginx/localhost.crt
    ports:
      - "8080:443"
    restart: unless-stopped
    networks:
      - Transcendence2.0

include:
  - ./monitoring/monitoring-docker-compose.yml

networks:
  Transcendence2.0:
