services:
  pong-api:
    # env_file: ./compose.env This does not work for interpolation inside docker compose. only in container. But if you include it from root you can use it
    # All interpolation is from pong.env (BUT YOU NEED TO USE LONG INCLUDE SYNTAX in root compose.yaml)
    image: pong-api-img #I don't see point it putting this in env file
    container_name: ${PONG_CONTAINER_NAME:-pong-api} #Make sense to put in env file
    build:
      context: ./ #No point to put in env
      dockerfile: Dockerfile #No need in env
    # volumes:
    #   - pong-api:/pong/pong-api/src/ # No volumes at final version
    # ports:
    #   - ${PONG_PORT:-3010}:${PONG_PORT:-3010} #remove it will not be exposed at final version, Port make sense to put in env
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    secrets:
      - wallet_private_key
    command: ["npm", "start"] #No need in env
    networks:
      - ${DOCKER_NETWORK:-Transcendence2.0} #Nice to have in env

secrets:
  wallet_private_key:
    file: ./wallet_private.key
# volumes:
#   pong-api:
#     name: pong-api
#     driver: local
#     driver_opts:
#       type: none
#       device: ./src/
#       o: bind
