FROM node:23

WORKDIR /app

# Install TypeScript and nodemon globally
RUN npm install -g typescript

# Copy your local package.json if needed (optional step)
COPY ./docker/typescript/config/package*.json ./
COPY ./docker/typescript/config/tsconfig.json ./
RUN npm install

CMD ["tsc", "--watch"]


