services:
  nginx:
    image: nginx:2
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx
    volumes:
      # - ./microservices/frontend/dist/:/usr/share/nginx/html
      - user_pictures:/usr/share/nginx/uploads:ro # Users pictures (Shared with Nginx, as read-only because nginx doesn't need to write into them)
      - vite_dist:/usr/share/nginx/html:ro # Compiled code by fronted service (Shared with Nginx, as read-only because nginx doesn't need to write into them)
      # - ./microservices/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:443"
    restart: unless-stopped
    networks:
      - Transcendence2.0

volumes:
  user_pictures:
  vite_dist:
