services:
  nginx:
    image: nginx:2
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx
    volumes:
      # - ./microservices/frontend/dist/:/usr/share/nginx/html
      # - user_pictures:/usr/share/nginx/html/uploads # Users pictures (Shared with Nginx)
      - vite_dist:/usr/share/nginx/html
      # - ./microservices/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:443"
    restart: unless-stopped
    networks:
      - Transcendence2.0

volumes:
  # user_pictures:
  vite_dist:
