FROM node:23

WORKDIR /app

# Install TypeScript and nodemon globally
RUN npm install -g typescript nodemon

# Copy your local package.json if needed (optional step)
COPY ./docker/typescript/config/package*.json ./
RUN npm install

CMD ["nodemon"]


