FROM alpine

WORKDIR /app

# Install necessary packages
RUN apk add --no-cache supervisor nodejs npm

RUN mkdir volume

COPY ./docker/tailwind/config/package*.json .

COPY ./docker/tailwind/config/supervisord.conf /etc/supervisord.conf

RUN npm install


# CMD ["npx @tailwindcss/cli -i /app/volume/css/input.css -o /app/volume/css/output.css --watch", "--poll"]
# CMD ["npx", "@tailwindcss/cli", "-i", "./volume/css/input.css", "-o", "./volume/css/output.css", "--watch", "--poll"]
# CMD ["node", "-e", "setInterval(() => {}, 1000)"]

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
