name: Comment Outdated Status
description: Posts or updates a comment on a PR to indicate it's outdated
inputs:
  pr_number:
    description: The pull request number
    required: true
  comment_body:
    description: The comment text to post
    required: true
  lookback_count:
    description: Number of recent comments to check for duplicates
    required: false
    default: "2"
runs:
  using: "composite"
  steps:
    - name: Comment about outdated status
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          const { owner, repo } = context.repo;
          const prNumber = Number("${{ inputs.pr_number }}");
          const commentBody = `${process.env.INPUT_COMMENT_BODY}`;
          const lookback = Number("${{ inputs.lookback_count }}");

          console.log(`💬 Checking for outdated comment on PR #${prNumber}...`);
          const { data: comments } = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number: prNumber,
          });

          const recent = comments.slice(-lookback);
          const alreadyPresent = recent.some(c => c.body === commentBody);

          if (alreadyPresent) {
            console.log("✅ Comment already present among last few — skipping.");
          } else {
            const old = comments.find(c => c.body === commentBody);
            if (old) {
              console.log("🧽 Removing older matching comment...");
              await github.rest.issues.deleteComment({
                owner,
                repo,
                comment_id: old.id,
              });
            }
            console.log("💬 Posting fresh outdated warning...");
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: commentBody,
            });
          }
