name: Remove Label If Present
description: Removes a label from a PR if it exists
inputs:
  label:
    description: The name of the label to remove (accessible as OUTDATED_LABEL in script)
    required: true
  pr_number:
    description: The pull request number
    required: true
runs:
  using: "composite"
  steps:
    - name: Remove label if present
      uses: actions/github-script@v7
      with:
        github-token: ${{ github.token }}
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const prNumber = Number("${{ inputs.pr_number }}");
          const labelName = process.env.OUTDATED_LABEL;

          console.log(`🧽 Attempting to remove label '${labelName}' from PR #${prNumber}...`);

          try {
            await github.rest.issues.removeLabel({
              owner,
              repo,
              issue_number: prNumber,
              name: labelName,
            });
            console.log(`➖ Label '${labelName}' removed.`);
          } catch (e) {
            if (e.status === 404) {
              console.log(`🚫 Label '${labelName}' not found on PR — nothing to remove.`);
            } else {
              throw e;
            }
          }
