name: 🐛 Bug Report (form)
description: Bug report in from format
title: "[BUG] Write here a short but meaningful title"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📋 Info
        Please fill out the sections below to help everyone identify and fix the bug.
        Required fields are marked with a red asterisk '*'.
        Use labels and assign users and project via GitHub interface if not auto-filled.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: 📝 Installed Node packages / VSCode extensions?
          required: true
        - label: 🔢 Followed `README.md` setup?
          required: true
        - label: 👀 Checked [GitHub Project webpage](https://github.com/users/marcorondong/projects/1) / [Discord](https://discord.com/channels/1267824540638249053/1267824540638249057) for known issues or temp instructions?
          required: true
  - type: textarea
    id: description
    attributes:
      label: 🗣️ Describe the bug
      placeholder: When I click here this happens.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 🧐 What should have happened?
      placeholder: I expected this to happen.
  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to reproduce the bug
      placeholder: |
        1. Go to page X.
        2. Click here.
        3. Click there.
    validations:
      required: true
  - type: dropdown
    id: services
    attributes:
      label: 🧩 Which services/codebase parts are involved? (multiple selection allowed)
      multiple: true
      options:
        - AI
        - AUTH
        - BLOCKCHAIN
        - CHAT
        - CLI_CLIENT
        - FRONTEND
        - MONITORING
        - PONG
        - TICTACTOE
        - USERS
        - Nginx
        - Node packages
        - docker-compose.yml
        - Makefile
        - Secrets (.txt files)
        - Environmental variables (.env files)
        - Scripts
        - GitHub
        - VS Code
  - type: textarea
    id: source
    attributes:
      label: 🧠 Where do you think the bug comes from?
      placeholder: The service X is not communicating with service Y.
  - type: textarea
    id: solution
    attributes:
      label: 🛠️ How do you think it can be fixed?
      placeholder: Change service Y url to match service X.
  - type: textarea
    id: links
    attributes:
      label: 🔗 Put here any useful links to help solve the bug, or to support why it's a bug.
      placeholder: |
        1. [Link 1](foo.com)
        2. [Link 2](bar.com)
        3. Or use "Paste, drop, or click to add files"
  - type: textarea
    id: media
    attributes:
      label: 📷 Put here any screenshots, files or videos (optional)
      placeholder: |
        1. [Screenshot or video](foo.com)
        2. [Logs or trace](bar.com)
        3. Or use "Paste, drop, or click to add files"
  - type: textarea
    id: extra
    attributes:
      label: 💬 Other Notes
      placeholder: Any extra info.
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Please use labels and assign users and project via GitHub interface if not auto-filled
        Thanks for reporting this bug! We will get back to you as soon as possible.
