name: 🚀 Feature Request (form)
description: Feature request  in from format
title: "[FEAT] Write here a short but meaningful title"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📋 Info
        Please fill out the sections below to help everyone implement the feature.
        Required fields are marked with a red asterisk '*'.
        Use labels and assign users and project via GitHub interface if not auto-filled.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: 👀 Checked [GitHub Project webpage](https://github.com/users/marcorondong/projects/1) / [Discord](https://discord.com/channels/1267824540638249053/1267824540638249057) for existing feature request?
          required: true
  - type: textarea
    id: description
    attributes:
      label: 🗣️ Describe the feature
      placeholder: I would like the Makefile to automatically check the required env/secrets files.
    validations:
      required: true
  - type: textarea
    id: justification
    attributes:
      label: 🧐 Why we should implement the feature?
      placeholder: Because we could easily identify what's missing, instead of losing 30min for the bug.
    validations:
       required: true
  - type: dropdown
    id: services
    attributes:
      label: 🧩 Which services/codebase parts are involved? (multiple selection allowed)
      multiple: true
      options:
        - AI
        - AUTH
        - BLOCKCHAIN
        - CHAT
        - CLI_CLIENT
        - FRONTEND
        - MONITORING
        - PONG
        - TICTACTOE
        - USERS
        - Nginx
        - Node packages
        - docker-compose.yml
        - Makefile
        - Secrets (.txt files)
        - Environmental variables (.env files)
        - Scripts
        - GitHub
        - VS Code
  - type: textarea
    id: solution
    attributes:
      label: 🛠️ How do you think it can be implemented?
      placeholder: We can add a new Makefile rule ('check').
  - type: textarea
    id: links
    attributes:
      label: 🔗 Put here any useful links to help implement the feature, or to support why it's useful.
      placeholder: |
        1. [Link 1](foo.com)
        2. [Link 2](bar.com)
        3. Or use "Paste, drop, or click to add files"
  - type: textarea
    id: media
    attributes:
      label: 📷 Put here any screenshots, files or videos (optional)
      placeholder: |
        1. [Screenshot or video](foo.com)
        2. [Logs or trace](bar.com)
        3. Or use "Paste, drop, or click to add files"
  - type: textarea
    id: extra
    attributes:
      label: 💬 Other Notes
      placeholder: Any extra info.
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
  - type: markdown
    attributes:
      value: |
        Please use labels and assign users and project via GitHub interface if not auto-filled
        Thanks for requesting this feature! We will get back to you as soon as possible.
