blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://discord.com/channels/1267824540638249053/1267824540638249057
    about: You can join the discussions on Discord.
  - name: Participating in our ft_transcendence
    url: https://github.com/marcorondong/transcendence2.0/blob/main/CONTRIBUTING.md
    about: Before opening a new issue or PR, please make sure to read CONTRIBUTING.md
  - name: Instructions for Devs.
    url: https://github.com/marcorondong/transcendence2.0/blob/main/README_DEV.md
    about: Your guide to set-up the project and useful information of it.
