services:
  ai-bot:
    image: ai-bot
    build:
      dockerfile: ./ai/docker/Dockerfile
    container_name: ai-bot
    volumes:
      - ./ai/src:/app/src:ro
    env_file:
      - ./ai/docker/.env
    restart: unless-stopped
    networks:
      - Transcendence2.0