services:
  ai-bot:
    image: ai-bot
    build:
      dockerfile: ./docker/Dockerfile
    container_name: ai-bot
    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./docker/.env
    restart: unless-stopped
    networks:
      - Transcendence2.0