services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173" # dev server port
    environment:
      - NODE_ENV=development # or production
    volumes:
      - .:/app # mount source code for dev
    networks:
      - Transcendence2.0
    restart: unless-stopped
