services:
  frontend:
    image: frontend:1.0.0
    container_name: frontend
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173" # TODO: close this before handing in
    environment:
      # - NODE_ENV=development # or production
      - NODE_ENV=production
    volumes:
      - .:/app # Mount full project
      - frontend_node_modules:/app/node_modules # Keep node_modules container-managed
      - vite_dist:/app/dist
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped
volumes:
  frontend_node_modules:
  vite_dist:
