services:
  frontend:
    image: frontend:V1.0.0
    container_name: frontend
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5173:5173" # TODO: close this before handing in
    environment:
      - NODE_ENV=development # or production
      # - NODE_ENV=production
    volumes:
      - .:/app
      - vite:/app/dist
    networks:
      - ${NETWORK_NAME}
    restart: unless-stopped

volumes:
  vite:
