services:
  tictactoe_db:
    image: ${TICTACTOE_DB_IMAGE_NAME}
    container_name: ${TICTACTOE_DB_CONTAINER_NAME}
    build: ${TICTACTOE_DB_BUILD_FOLDER}
    env_file:
      - ../service.config
    volumes:
      - ${TICTACTOE_DB_SRC_FOLDER_LOCAL}:${TICTACTOE_DB_SRC_FOLDER_CONTAINER} #TODO remove in production
      - ${TICTACTOE_DB_PRISMA_FOLDER_LOCAL}:/${TICTACTOE_DB_PRISMA_FOLDER_CONTAINER} #TODO remove in production
      #- ${TICTACTOE_DB_DATABASE_FOLDER_LOCAL}:${TICTACTOE_DB_DATABASE_FOLDER_CONTAINER} #TODO define path to db and uncomment this line when using the local DB
    ports:
      - ${TICTACTOE_DB_PORT}:${TICTACTOE_DB_PORT}
    networks:
      - ${NETWORK_NAME}
    restart: ${RESTART_POLICY}
