services:
  tictactoe_db:
    image: tictactoe_db_image
    container_name: tictactoe_db_container
    build: ./
    env_file:
      - ../../setting.conf
    volumes:
      # - ./src/:/tictactoe_db/src/ #TODO remove in production
      # - ./prisma/:/tictactoe_db/prisma/ #TODO remove in production
      - tictactoe_db:/tictactoe_db/DB/ #TODO define path to db and uncomment this line when using the local DB
    ports:
      - 3003:3003 # TODO remove this in production
    networks:
      - Transcendence2.0
    restart: unless-stopped

volumes:
  tictactoe_db:
