services:
  ai-bot:
    build: .
    container_name: ai-bot
    ports:
      - "6969:6969"
    environment:
      - NODE_ENV=production
    networks:
      - Transcendence2.0

networks:
  Transcendence2.0:
    external: true  #REMOVE external network if we use 1 single docker-compose for all services
