# Sample config for Prometheus.

#global:
#  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
#  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
# scrape_timeout is set to the global default (10s).

# Attach these labels to any time series or alerts when communicating with
# external systems (federation, remote storage, Alertmanager).
# external_labels:
#    monitor: 'example'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

# Override the global default and scrape targets from this job every 5 seconds.
# scrape_interval: 5s
# scrape_timeout: 5s

# metrics_path defaults to '/metrics'
# scheme defaults to 'http'.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "blackbox_exporter"
    static_configs:
      - targets: ["blackbox-exporter:9115"]

#monitor backend endpoints in docker network
  - job_name: 'blackbox-http'
    scrape_interval: 10m
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://ai-bot:6969/health-check
        - http://pong-api:3010/pong-api/health-check
        - http://pong_db_container:3011/pong/health-check
        - http://tictactoe_db:3003/tictactoe-db/health-check
        - http://tictactoe_api:3001/tictactoe-api/health-check
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

#monitor user endpoints but in docker network
  - job_name: "blackbox-https"
    scrape_interval: 10m
    metrics_path: /probe
    params:
      module: [https_no_verify]
    static_configs:
      - targets:
          - https://frontend:443
          - https://frontend:443/users
          - https://frontend:443/profile
          - https://frontend:443/highscore
        #frontend:443 is mounted to localhost:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
