FROM node:22-slim

WORKDIR /app

# Install necessary packages
RUN apt-get update && apt-get install -y \
  supervisor \
  nodejs \
  npm \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir volume

COPY ./docker/tailwind/config/package*.json .

COPY ./docker/tailwind/config/supervisord.conf /etc/supervisord.conf


RUN npm install



CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
