services:
  auth_api:
    image: ${AUTH_API_IMAGE_NAME}
    container_name: ${AUTH_API_CONTAINER_NAME}
    build: ${AUTH_API_BUILD_FOLDER}
    env_file:
      - ../service.config
    secrets:
      - jwtSecret.key
      - cookieSecret.key
    volumes:
      - ${AUTH_API_SRC_FOLDER_LOCAL}:${AUTH_API_SRC_FOLDER_CONTAINER} #TODO remove in production
    ports:
      - ${AUTH_API_PORT}:${AUTH_API_PORT}
    networks:
      - ${NETWORK_NAME}
    restart: ${RESTART_POLICY}

secrets:
  jwtSecret.key:
    file: ${AUTH_API_JWT_SECRET_FILE_LOCATION_LOCAL}
  cookieSecret.key:
    file: ${AUTH_API_COOKIE_SECRET_FILE_LOCATION_LOCAL}
