services:
  auth_api:
    image: auth_api_img
    container_name: auth_api_container
    build: .
    volumes:
      - ./src/:/auth_api/src/ # TODO remove this in production
    environment: # receive env variables from .env file
      - NODE_ENV=development
      - PORT=2999
      - HOST=0.0.0.0
      - JWT_SECRET_FILE=/run/secrets/jwtSecret.key
      - COOKIE_SECRET_FILE=/run/secrets/cookieSecret.key
    secrets:
      - jwtSecret.key
      - cookieSecret.key
    ports: # TODO remove this in production
      - 2999:2999
    networks:
      - Transcendence2.0
    restart: always

secrets:
  jwtSecret.key:
    file: ./secret_keys/jwtSecret.key
  cookieSecret.key:
    file: ./secret_keys/cookieSecret.key
