services:
  auth_api:
    image: auth_api_image
    container_name: auth_api_container
    build: ./
    env_file:
      - ../../setting.conf
    secrets:
      - jwtSecret.key
      - cookieSecret.key
    volumes:
      - ./src/:/auth_api/src/ #TODO remove in production
    ports:
      - 2999:2999 # TODO remove this in production
    networks:
      - Transcendence2.0
    restart: always

secrets:
  jwtSecret.key:
    file: ./secret_keys/jwtSecret.key
  cookieSecret.key:
    file: ./secret_keys/cookieSecret.key
