services:
  pong_db:
    image: pong_db_image
    container_name: pong_db_container
    build: ./
    env_file:
      - ../../setting.conf
    volumes:
      # - ./src/:/pong_db/src/ #TODO remove in production
      # - ./prisma/:/pong_db/prisma/ #TODO remove in production
      - pong_db:/pong_db/DB/
    # ports:
    #   - 3011:3011 # TODO remove this in production
    networks:
      - Transcendence2.0
    restart: unless-stopped

volumes:
  pong_db: