services:
  pong_db:
    image: pong_db_image
    container_name: pong_db_container
    build: ./
    env_file:
      - ../../setting.conf
    volumes:
      - ./src/:/pong_db/src/ #TODO remove in production
      - ./prisma/:/pong_db/prisma/ #TODO remove in production
      #- /home/iguliyev/DBs/pong/:/pong_db/DB/ #TODO define path to db and uncomment this line when using the local DB
    ports:
      - 3011:3011 # TODO remove this in production
    networks:
      - Transcendence2.0
    restart: always