services:
  pong_db:
    image: ${PONG_DB_IMAGE_NAME}
    container_name: ${PONG_DB_CONTAINER_NAME}
    build: ${PONG_DB_BUILD_FOLDER}
    env_file:
      - ${PONG_DB_ENV_FILE_PATH}
    volumes:
      - ${PONG_DB_SRC_FOLDER_LOCAL}:${PONG_DB_SRC_FOLDER_CONTAINER} #TODO remove in production
      - ${PONG_DB_PRISMA_FOLDER_LOCAL}:/${PONG_DB_PRISMA_FOLDER_CONTAINER} #TODO remove in production
      #- ${PONG_DB_DATABASE_FOLDER_LOCAL}:${PONG_DB_DATABASE_FOLDER_CONTAINER} #TODO define path to db and uncomment this line when using the local DB
    ports:
      - ${PONG_DB_PORT}:${PONG_DB_PORT}
    networks:
      - ${NETWORK_NAME}
    restart: ${RESTART_POLICY}
