services:
  pong_db:
    image: pong_db_image
    container_name: pong_db_container
    build: .
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=file:/pong_db/DB/pongDB.db
    volumes:
      - ./src/:/pong_db/src/
      - ./prisma/:/pong_db/prisma/
      - /home/iguliyev/DBs/pong/:/pong_db/DB/
    ports:
      - 3011:3011
    restart: always
