{
 "title": "Endpoints availability",
 "tags": [ "endpoints_availability" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Probe success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Probe status code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Blackbox config loaded",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blackbox_exporter_config_last_reload_successful{instance=\"blackbox-exporter:9115\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average respose time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}