{
 "title": "Host system",
 "tags": [ "host_sys_monitor" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU usage in %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", instance=\"node-exporter:9100\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node_exporter\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Disk available",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Chip temperature sensors",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"node-exporter:9100\",job=\"node_exporter\"} * on(chip) group_left(chip_name) node_hwmon_chip_names{instance=\"node-exporter:9100\",job=\"node_exporter\"}\n",
     "legendFormat": "{{ chip_name }}"
    }
   ]
  },
  {
   "title": "fan speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{instance=\"node-exporter:9100\",job=\"node_exporter\"}",
     "legendFormat": "fan rpm"
    },
    {
     "expr": "node_hwmon_fan_min_rpm{instance=\"node-exporter:9100\",job=\"node_exporter\"}",
     "legendFormat": "fan min rpm"
    }
   ]
  },
  {
   "title": "power supply",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_power_supply_info", "legendFormat": "{{power_supply}}" }
   ]
  },
  {
   "title": "power supply capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "node_power_supply_capacity", "legendFormat": "{{power_supply}}" }
   ]
  },
  {
   "title": "voltage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_power_supply_voltage_volt", "legendFormat": "{{power_supply}}" }
   ]
  }
 ]
}