{
 "title": "Network",
 "tags": [ "network_monitor" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "TCP active/passive connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens[5m])",
     "legendFormat": "TCP active connections"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens[5m])",
     "legendFormat": "TCP passive connections"
    }
   ]
  },
  {
   "title": "TCP segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_InSegs[5m])",
     "legendFormat": "In segments"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs[5m]) * -1",
     "legendFormat": "out segments"
    }
   ]
  },
  {
   "title": "UPD datagrams received/sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InDatagrams[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_netstat_Udp_OutDatagrams[5m]) * -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYNs to LISTEN sockets ignored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_netstat_TcpExt_ListenDrops",
     "legendFormat": "listen drops"
    }
   ]
  },
  {
   "title": "SYN retransmits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_TCPSynRetrans[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Socket usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "node_sockstat_sockets_used", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Netstat octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "irate(node_netstat_IpExt_InOctets[5m])",
     "legendFormat": "octets in"
    },
    {
     "expr": "irate(node_netstat_IpExt_OutOctets[5m])",
     "legendFormat": "octets out"
    }
   ]
  },
  {
   "title": "TCP sockets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "node_sockstat_TCP_alloc", "legendFormat": "allocated TCP sockets" },
    { "expr": "node_sockstat_TCP_inuse", "legendFormat": "TCP sockets in use" }
   ]
  },
  {
   "title": "TCP memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_sockstat_TCP_mem_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UPD socket usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "node_sockstat_UDPLITE_inuse + node_sockstat_UDP_inuse",
     "legendFormat": "UDP + UDPLITE sockets in use"
    }
   ]
  },
  {
   "title": "UDP sockets memory usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_sockstat_UDP_mem", "legendFormat": "__auto" }
   ]
  }
 ]
}