services:
  chat_api:
    image: chat_api_img 
    container_name: chat_api
    build: ./
    volumes:
      - ./src/:/chat_api/src/
    ports:
      - 3002:3002
    secrets:
      - cert.pem
      - key.pem
    environment:
      SSL_CERT_FILE: "/run/secrets/cert.pem"
      SSL_KEY_FILE: "/run/secrets/key.pem"

secrets:
  cert.pem:
    file: ./server-keys/cert.pem
  key.pem:
    file: ./server-keys/key.pem