services:
  tictactoe_api:
    image: tictactoe_api_image
    container_name: tictactoe_api_container
    build: ./
    env_file:
      - ../../setting.conf
    volumes:
      - ./src/:/tictactoe_api/src/ # TODO remove this in production
    ports:
      - 3001:3001 # TODO remove this in production
    networks:
      - Transcendence2.0
    depends_on:
      - tictactoe_db
    restart: unless-stopped
