services:
  tictactoe_api:
    image: ${TICTACTOE_API_IMAGE_NAME}
    container_name: ${TICTACTOE_API_CONTAINER_NAME}
    build: ${TICTACTOE_API_BUILD_FOLDER}
    env_file:
      - ../service.config
    volumes:
      - ${TICTACTOE_API_SRC_FOLDER_LOCAL}:${TICTACTOE_API_SRC_FOLDER_CONTAINER} # TODO remove this in production
      - ./public/:/tictactoe_api/public/ # TODO remove this when there is real frontend
    ports:
      - ${TICTACTOE_API_PORT}:${TICTACTOE_API_PORT} # TODO remove this in production
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - ${TICTACTOE_DB_MICRO_SERVICE_NAME}
    restart: ${RESTART_POLICY}

