services:
  tictactoe_api:
    image: tictactoe_img 
    container_name: tictactoe_container
    build: .
    environment:
      - DATABASE_URL=file:/tictactoe_api/DB/tictactoe.db
    volumes:
      - ./src/:/tictactoe_api/src/
      - ./prisma/:/tictactoe_api/prisma/
      - ./public/:/tictactoe_api/public/
      # - /home/iguliyev/DBs/tictactoe/:/tictactoe_api/DB/ # TODO uncomment this line when using the local DB
    ports:
      - 3001:3001
    restart: always

    
  tictactoe_db:
    image: tictactoe_db_img 
    container_name: tictactoe_db_container
    build: ../tictactoe_db
    environment:
      - DATABASE_URL=file:/tictactoe_db/DB/tictactoeDB.db
    volumes:
      - ../tictactoe_db/src/:/tictactoe_db/src/
      - ../tictactoe_db/prisma/:/tictactoe_db/prisma/
      # - ./public/:/tictactoe_api/public/
      # - /home/iguliyev/DBs/tictactoe/:/tictactoe_api/DB/ # TODO uncomment this line when using the local DB
    ports:
      - 3003:3003
    restart: always