services:
  tictactoe_api:
    image: tictactoe_api_img 
    container_name: tictactoe_api
    build: ./
    volumes:
      - ./src/:/tictactoe_api/src/
    ports:
      - 3001:3001
    secrets:
      - cert.pem
      - key.pem
    environment:
      SSL_CERT_FILE: "/run/secrets/cert.pem"
      SSL_KEY_FILE: "/run/secrets/key.pem"

secrets:
  cert.pem:
    file: ./server-keys/cert.pem
  key.pem:
    file: ./server-keys/key.pem