# version: "3.9"

services:
  users:
    image: users:V1.0.0
    container_name: users
    build:
      context: .
      dockerfile: docker/Dockerfile
    secrets:
      - apikey
    volumes:
      # - .:/app # Mount full project
      - users_node_modules:/app/node_modules # Keep node_modules container-managed
      - ./database:/app/prisma/database # Keep DB container-managed & ephemeral
      - user_pictures:/app/uploads # Users pictures (Shared with Nginx)
    ports:
      - "3000:3000" # Expose Fastify server to host
    # environment:
    #   - DATABASE_URL=file:./prisma/database/dev.db
    networks:
      - Transcendence2.0
    # command: >
    #   sh -c "npx prisma migrate reset --force --skip-seed &&
    #          RUNNING_ENV=container npm run dev"

secrets:
  apikey:
    file: docker/apikey.txt

volumes:
  users_node_modules:
  user_pictures:
