name: Run Playwright Tests
on: # specifies when workflow is run
  workflow_dispatch:  # enables manually starting workflow on a given branch (through Actions tab in Repo)
  push: # run workflow when a git push into a branch happens
    branches: [ main ] # specify which branches
  pull_request: # run workflow when a pull request into a branch is opened
    branches: [ main ]
    paths:
      - '**'  # include all files
      - '!.notes/**' # exclude files in .notes/ folder
      - '!doc/**' # exclude files in doc/ folder

jobs:
  start-app-and-run-tests:
    name: Start App and Run Tests
    timeout-minutes: 30
    runs-on: ubuntu-22.04

    env:
      PLAYWRIGHT_DIR: tests/playwright/tools

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run App
        uses: ./.github/actions/run-app

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies and Playwright Browsers
        run: |
          cd $PLAYWRIGHT_DIR
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          cd $PLAYWRIGHT_DIR
          npx playwright test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ${{ env.PLAYWRIGHT_DIR }}/playwright-report/
          retention-days: 30